/* ------------------------------------------------------------------------------------------------------------------ */
/*    _____  __              __ __                                                                                    */
/*   |     \|__|.-----.----.|__|  |_.-----.                                                                           */
/*   |  --  |  ||  _  |   _||  |   _|  -__|                                                                           */
/*   |_____/|__||_____|__|  |__|____|_____|                                                                           */
/*                                                                                                                    */
/* ------------------------------------------------------------------------------------------------------------------ */
/* This is the grammar specification for the Diorite mathematics computing language.                                  */
/* This specifictaion uses a mix of BNF and the 'syntax' sugar of EBNF for multiplcity definitions of rule repitions. */
/* Each rule is a stage/function in the LL(1) (recursive descent) parser.                                             */
/* This specification is written bottom-top to show the composition of these rules.                                   */
/* This grammar was written with 'BNF Playground' (https://bnfplayground.pauliankline.com)                            */
/* Be aware, that when using this BNF parser it may produce false positives, such as partial strings of optional      */
/* values. For example: '2+' produces a false positive as it only partially respects the <Term> rule. The parser may  */
/* be too permissive for this grammar but its the only way to write such a grammar without tearing my hair out in     */
/* frustration. This grammar will strictly comply with the grammar and not implement these partial values.            */
/* Whitespace is implied by this grammar - UNLESS SPECIFIED OTHERWISE                                                 */
/* ------------------------------------------------------------------------------------------------------------------ */

/* ------------------------------------------------------------------------------------------------------------------ */
/* ADDITIONAL INFO:                                                                                                   */
/* - The character '_' is the equivalent to the ANS or ANSWER button on a calculator, hence it represents the result  */
/*   of the previous expression                                                                                       */
/* ------------------------------------------------------------------------------------------------------------------ */

/* Value Types */
<Number>                 ::= ([0-9]+ ("." [0-9]+)?)
<Variable>               ::= [a-z] | [A-Z] | "_"

/* Grouping Type (Final Stage of Parser) */
<Atom>                   ::= <Number> | <Variable>

/* Operations: Unary */
<Factorial>              ::= (<Atom> "!"*) | ("(" (<Term> | <Builtin> | <FunctionExecution>) ")")
<Signed>                 ::= ("+" | "-")* <Factorial>

/* Operations: Binary */
<Exponent>               ::= <Signed> ("^" <Signed>)*
<Factor>                 ::= <Exponent> (("*" | "/") <Exponent>)*
<Term>                   ::= <Factor>+ (("+" | "-" | "%") <Factor>)*
<Expression>             ::= (<Term> | <Builtin> | <FunctionExecution>) | ("(" (<Term> | <Builtin> | <FunctionExecution>) ")")+

/* ------------------------------------------------------------------------------------------------------------------ */
/* Expression Examples:                                                                                               */
/* a^2 + b^2 - 4ac                  -> a^2+b^2-4ac (as per the BNF)                                                   */
/* f(g(x)) + f(x) * g(x) - (4y % 4) -> f(g(x))+f(x)*g(x)-(4y%4) (as per the BNF)                                      */
/* ------------------------------------------------------------------------------------------------------------------ */

/* Function Conditionals */
<If>                     ::= <Expression> "if" <Expression> ("=" | "!=" | "<" | ">" | "<=" | ">=") <Expression>
<Else>                   ::= <Expression> "otherwise"
<Conditions>             ::= <If> ((" " | "\n")+ <If>)* (" " | "\n")+ <Else>

/* Functions */
<FunctionParams>         ::= <Variable> ("," <Variable>)*
<FunctionArguments>      ::= <Expression> ("," <Expression>)*
<FunctionDefinition>     ::= <Variable> "(" <FunctionParams> ")"
<FunctionBody>           ::= <Expression> | "{" <Conditions> "}"
<FunctionExecution>      ::= <Variable> "(" <FunctionArguments> ")"

/* Builtin Functions - they are functions with identifiers with character count of at least 1 so using generic form   */
<Builtin>                ::= [a-z]+ "(" <FunctionArguments> ")"

/* ------------------------------------------------------------------------------------------------------------------ */
/* Fibonacci Example:                                                                                                 */
/* F(x) = {                                                                                                           */
/*     x                   if x <= 1                                                                                  */
/*     F(x - 2) + F(x - 1) otherwise                                                                                  */
/* }                                                                                                                  */
/* ------------------------------------------------------------------------------------------------------------------ */
/* As per the BNF:                                                                                                    */
/* F(x)={(x)if(x)<=(1) F(x-2)+F(x-1)otherwise}                                                                        */
/* (Whitespace is required for seperating function conditionals)                                                      */
/* ------------------------------------------------------------------------------------------------------------------ */

/* Equations */
<Equation>               ::= (<Expression> "=" <Expression>)
                          | (<FunctionDefinition> "=" <Expression>)
                          | <Expression> "=" <FunctionDefinition>

/* ------------------------------------------------------------------------------------------------------------------ */
/* Equation Examples:                                                                                                 */
/* y = mx + c         -> y=mx+c (as per the BNF)                                                                      */
/* f(m) = g(m) + h(m) -> f(m)=g(m)+h(m) (as per the BNF)                                                              */
/* f(x) = 2y + x      -> f(x)=2y+x (as per the BNF) - provided y is defined                                           */
/* ------------------------------------------------------------------------------------------------------------------ */

/* Entry Point */
<Diorite>                ::= <Equation> | <Expression>

/* ------------------------------------------------------------------------------------------------------------------ */
/* Diorite | Developed and produced by Arsngrobg and Borngle | 2025                                                   */
/* ------------------------------------------------------------------------------------------------------------------ */
