/* ------------------------------------------------------------------------------------------------------------------ */
/*    _____  __              __ __                                                                                    */
/*   |     \|__|.-----.----.|__|  |_.-----.                                                                           */
/*   |  --  |  ||  _  |   _||  |   _|  -__|                                                                           */
/*   |_____/|__||_____|__|  |__|____|_____|                                                                           */
/*                                                                                                                    */
/* ------------------------------------------------------------------------------------------------------------------ */
/* The grammar specification for the Diorite mathematics computing language.                                          */
/* Whitespace is implied by this grammar (unless specified or enforced otherwise)                                     */
/* ε is the 'epsilon' character, which denotes an empty string                                                        */
/* ------------------------------------------------------------------------------------------------------------------ */

/* base defs */
<DQString> ::= "\"" <StringContent> "\""
<StringContent> ::= ε
                  | <Char> <StringContent>
<Char> ::= any character except "\""

<Digit> ::= "0" | "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9"

<Letter> ::= "a" | "b" | ... | "z" | "A" | "B" | ... | "Z"

<Variable> ::= <Letter>
             | <Letter> <Digit>
             | <Letter> <Letter>
             | <Letter> <Letter> <Digit>

<Value> ::= <Number>
          | <DQString>

<Number> ::= <Digit>
           | <Digit> <Digit>
           | <Digit> "." <Digit>
           | <Digit> <Digit> "." <Digit>

<Expression> ::= <Expression> "+" <Term>
               | <Expression> "-" <Term>
               | <Term>

<Term> ::= <Term> "*" <Factor>
         | <Term> "/" <Factor>
         | <Factor>

<Factor> ::= <SubExpression> "^" <Factor>
           | <SubExpression>

<SubExpression> ::= "complex" "(" <Expression> "," <Expression> ")"
                  | "im" <SubExpression>
                  | "re" <SubExpression>
                  | <FunctionCall>
                  | "(" <Expression> ")"
                  | "|" <Expression> "|"
                  | <Variable>
                  | <Value>

<FunctionCall> ::= <Variable> "(" <Args> ")"
                 | <Symbol> "(" <Args> ")"

<Args> ::= <Expression>
         | <Expression> "," <Args>

<Assignment> ::= <Variable> "=" <Expression>

<FunctionResult> ::= <Expression>
                   | "error" <DQString>
                   | "error"

<ComparisonOperator> ::= "=" | "!=" | "<" | "<=" | ">" | ">="

<ComparisonOperation> ::= <Expression> <ComparisonOperator> <Expression>

<PiecewiseIf> ::= <Expression> "if" <ComparisonOperation>

<PiecewiseOtherwise> ::= <Expression> "otherwise"

<PiecewiseConditions> ::= <PiecewiseIf> ";" <PiecewiseConditions>
                        | <PiecewiseIf> ";" <PiecewiseOtherwise> ";"

<FunctionBody> ::= <Expression> ";"
                 | "{" <PiecewiseConditions> "}"

<Parameter> ::= <Letter>
              | <Letter> ":" <NumberSet>

<Parameters> ::= <Parameter> "," <Parameters>
               | <Parameter>

<ReturnSet> ::= ε
              | "->" <NumberSet>

<FunctionMeta> ::= "[" "symbol" ":" <Letters> "]" <FunctionMeta>
                 | "[" "inline" "]" <FunctionMeta>
                 | "[" "memoized" "]" <FunctionMeta>

<FunctionHead> ::= <Variable> "(" <Parameters> ")" <ReturnSet>

<FunctionDefinition> ::= <FunctionHead> "=" <FunctionBody>

<PlotExpression> ::= "plot" <Expression>
                   | "plot" <Expression> "using" <Variable>

<Statement> ::= ε
              | ";" <Statement>
              | <Expression> ";" <Statement>
              | <PlotExpression> ";" <Statement>
              | <Assignment> ";" <Statement>
              | <FunctionDefinition> <Statement>

/* ------------------------------------------------------------------------------------------------------------------ */
/* Diorite | Developed and produced by Arsngrobg and Borngle | 2025                                                   */
/* ------------------------------------------------------------------------------------------------------------------ */
