<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net9.0</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
        <Compile Include="BaseTypes.fsi" />
        <Compile Include="BaseTypes.fs"  />
        <Compile Include="Errors.fsi"    />
        <Compile Include="Errors.fs"     />
        <Compile Include="Lexer.fsi"     />
        <Compile Include="Lexer.fs"      />
    </ItemGroup>

</Project>
