<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Library</OutputType>
        <TargetFramework>net10.0</TargetFramework>
    </PropertyGroup>

    <!-- Syntax -->
    <ItemGroup>
        <Compile Include="Syntax\ValueType.fs"             />
        <Compile Include="Syntax\VariableType.fs"          />
        <Compile Include="Syntax\NumberSet.fs"             />
        <Compile Include="Syntax\TokenType.fs"             />
        <Compile Include="Syntax\TokenValue.fs"            />
        <Compile Include="Syntax\Token.fs"                 />
        <Compile Include="Syntax\BinaryOperator.fs"        />
        <Compile Include="Syntax\UnaryOperator.fs"         />
        <Compile Include="Syntax\ComparisonOperator.fs"    />
        <Compile Include="Syntax\FunctionReferenceType.fs" />
        <Compile Include="Syntax\Expression.fs"            />
        <Compile Include="Syntax\FunctionResult.fs"        />
        <Compile Include="Syntax\ComparisonOperation.fs"   />
        <Compile Include="Syntax\PiecewiseCondition.fs"    />
        <Compile Include="Syntax\FunctionMetadata.fs"      />
        <Compile Include="Syntax\FunctionParameter.fs"     />
        <Compile Include="Syntax\FunctionAttributes.fs"    />
        <Compile Include="Syntax\FunctionBody.fs"          />
        <Compile Include="Syntax\FunctionType.fs"          />
        <Compile Include="Syntax\ASTNode.fs"               />
        <Compile Include="Syntax\AST.fs"                   />
        <Compile Include="Syntax\Constants.fs"             />
    </ItemGroup>

    <ItemGroup>
        <Compile Include="Properties.fs" />
        <Compile Include="Syntax.fs"     />
        <Compile Include="Errors.fs"     />
        <Compile Include="Lexer.fs"      />
        <Compile Include="Parser.fs"     />
    </ItemGroup>

</Project>
